'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {SVGLoader} from 'three/addons/loaders/SVGLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {Pause,Play,RotateCcw,Plus,Minus,MoveUpRight,Zap,Radio} from 'lucide-react';
export type MapAsset={id:string;name:string;sector:string;kind:string;division:string;lat:number;lon:number;owner:string;capacity:string;status:string};
type Boundary={name:string;division:string;path:string};
const point=(a:MapAsset)=>new THREE.Vector3((a.lon-88)*132+70-350,13,(26.7-a.lat)*115+35-350);
export default function InfrastructureScene({geo,assets,dark,sector,division,connections,onSelect,onFallback}:{geo:Boundary[];assets:MapAsset[];dark:boolean;sector:string;division:string;connections:boolean;onSelect:(a:MapAsset)=>void;onFallback:()=>void}){
const host=useRef<HTMLDivElement>(null),api=useRef<{zoom:(n:number)=>void;reset:()=>void;focus:(id:string)=>void}|null>(null),callback=useRef(onSelect),[hover,setHover]=useState<MapAsset|null>(null),[active,setActive]=useState<MapAsset|null>(null),[moving,setMoving]=useState(false),[failed,setFailed]=useState(false);const rotating=useRef(false);callback.current=onSelect;rotating.current=moving;
const key=assets.map(a=>a.id).join(',');
useEffect(()=>{if(!host.current||!geo.length)return;setFailed(false);setActive(null);setHover(null);const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=dark?1.6:1.2;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','3D Bangladesh infrastructure. Drag to orbit, scroll to zoom. Select a pylon or tower to inspect.');renderer.domElement.tabIndex=0;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,1,4000);camera.position.set(130,710,690);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=270;controls.maxDistance=1600;controls.minPolarAngle=.16;controls.maxPolarAngle=1.22;controls.autoRotateSpeed=.35;controls.enablePan=true;controls.listenToKeyEvents(renderer.domElement);controls.update();controls.saveState();
scene.add(new THREE.HemisphereLight(dark?0xd5f7ff:0xffffff,dark?0x17364b:0x7a98ad,2.4));const sun=new THREE.DirectionalLight(0xffe8c6,3.2);sun.position.set(-350,650,200);scene.add(sun);const rim=new THREE.DirectionalLight(sector==='Electricity'?0xffa640:0x49bfff,3);rim.position.set(450,220,-250);scene.add(rim);
const mapGroup=new THREE.Group();scene.add(mapGroup);const loader=new SVGLoader();const groups=new Map<string,THREE.BufferGeometry[]>();for(const f of geo){const parsed=loader.parse(`<svg xmlns="http://www.w3.org/2000/svg"><path d="${f.path}"/></svg>`);for(const p of parsed.paths)for(const shape of SVGLoader.createShapes(p)){const g=new THREE.ExtrudeGeometry(shape,{depth:13,bevelEnabled:false,steps:1,curveSegments:1});const arr=groups.get(f.division)||[];arr.push(g);groups.set(f.division,arr)}}
const colors:Record<string,number>={Dhaka:0x427d79,Chattogram:0x376b75,Khulna:0x477c69,Barishal:0x528875,Rajshahi:0x416f64,Rangpur:0x5c8b76,Sylhet:0x426e70,Mymensingh:0x548178};for(const [name,geometries] of groups){const combined=mergeGeometries(geometries);geometries.forEach(g=>g.dispose());if(!combined)continue;const muted=division!=='All Bangladesh'&&division!==name;let color=new THREE.Color(colors[name]||0x427b73);if(!dark)color.lerp(new THREE.Color(0xe1f3eb),.72);if(sector==='Telecom')color.lerp(new THREE.Color(dark?0x234e80:0xc0dbf5),.4);if(sector==='Electricity')color.lerp(new THREE.Color(dark?0x74653b:0xf3e6c8),.22);const material=new THREE.MeshStandardMaterial({color,roughness:.55,metalness:.25,transparent:muted,opacity:muted?.22:1});const mesh=new THREE.Mesh(combined,material);mesh.rotation.x=Math.PI/2;mesh.position.set(-350,12,-350);mapGroup.add(mesh);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(combined,35),new THREE.LineBasicMaterial({color:dark?0x72c2b0:0x8ba99c,transparent:true,opacity:muted?.07:dark?.2:.24}));edge.rotation.copy(mesh.rotation);edge.position.copy(mesh.position);mapGroup.add(edge)}
const grid=new THREE.GridHelper(1250,36,dark?0x285368:0xa9c5d0,dark?0x1c3546:0xd6e3e8);grid.position.y=-8;const gm=grid.material as THREE.Material;gm.transparent=true;gm.opacity=.3;scene.add(grid);
const metal=new THREE.MeshStandardMaterial({color:dark?0xc5dedf:0x536d7b,metalness:.78,roughness:.28});const concrete=new THREE.MeshStandardMaterial({color:dark?0x314a55:0xd5dde0,metalness:.12,roughness:.8});const white=new THREE.MeshStandardMaterial({color:0xe4eff3,metalness:.4,roughness:.3});const powerMat=new THREE.MeshStandardMaterial({color:0xf2bc58,metalness:.5,roughness:.25,emissive:0x814409,emissiveIntensity:.25});const telecomMat=new THREE.MeshStandardMaterial({color:0x7ad4ff,metalness:.6,roughness:.22,emissive:0x0075c9,emissiveIntensity:.5});
function beam(parent:THREE.Group,a:number[],b:number[],radius=.65,mat=metal){const start=new THREE.Vector3(...a as [number,number,number]),end=new THREE.Vector3(...b as [number,number,number]),d=end.clone().sub(start);const m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,d.length(),5),mat);m.position.copy(start.add(end).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());parent.add(m)}
function box(parent:THREE.Group,size:number[],pos:number[],mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(...size as [number,number,number]),mat);m.position.set(...pos as [number,number,number]);parent.add(m);return m}
const models=new Map<string,THREE.Group>(),hits:THREE.Object3D[]=[],rings:{mesh:THREE.Mesh,offset:number}[]=[],particles:{mesh:THREE.Mesh,curve:THREE.Curve<THREE.Vector3>,offset:number}[]=[];
for(const a of assets){const model=new THREE.Group();model.position.copy(point(a));model.userData.asset=a;scene.add(model);models.set(a.id,model);const isPower=a.sector==='Electricity',accent=isPower?powerMat:telecomMat;box(model,[24,3,22],[0,1,0],concrete);const ys=isPower?[3,16,30,44,58]:[3,16,29,42,56];const widths=isPower?[9,7,4.8,3,1.2]:[7,5.5,4,2.5,1];for(let i=0;i<ys.length-1;i++){const lo=widths[i],hi=widths[i+1];for(const [sx,sz] of [[1,1],[1,-1],[-1,1],[-1,-1]]){beam(model,[lo*sx,ys[i],lo*sz],[hi*sx,ys[i+1],hi*sz],.7);beam(model,[lo*sx,ys[i],lo*sz],[-hi*sx,ys[i+1],hi*sz],.38);beam(model,[lo*sx,ys[i],lo*sz],[hi*sx,ys[i+1],-hi*sz],.38)}}
if(isPower){for(const [y,w] of [[31,18],[43,15],[53,11]]){beam(model,[-w,y,0],[w,y,0],1.05,accent);beam(model,[-w,y,0],[0,y+7,0],.55);beam(model,[w,y,0],[0,y+7,0],.55);for(const x of [-w,w]){beam(model,[x,y,0],[x,y-6,0],.8,white);for(let k=0;k<3;k++){const disc=new THREE.Mesh(new THREE.CylinderGeometry(1.5,1.5,.6,8),telecomMat);disc.position.set(x,y-1.5-k*1.5,0);model.add(disc)}}}box(model,[8,8,7],[15,5,7],powerMat);box(model,[7,6,7],[-15,4,7],metal)}else{beam(model,[0,52,0],[0,68,0],.8);for(let i=0;i<3;i++){const angle=i*Math.PI*2/3;const x=Math.cos(angle)*5,z=Math.sin(angle)*5;beam(model,[0,46,0],[x,46,z],.7);const antenna=box(model,[3,13,2.5],[x,50,z],white);antenna.rotation.y=-angle;box(model,[3.3,2,2.8],[x,55,z],telecomMat)}const dish=new THREE.Mesh(new THREE.SphereGeometry(4,12,8,0,Math.PI*2,0,Math.PI/2),white);dish.rotation.z=Math.PI/2;dish.position.set(6,34,0);model.add(dish);box(model,[9,10,8],[13,6,0],concrete);for(let k=0;k<2;k++){const ring=new THREE.Mesh(new THREE.TorusGeometry(12,.28,5,48),new THREE.MeshBasicMaterial({color:0x58c6ff,transparent:true,opacity:.4,depthWrite:false}));ring.rotation.x=Math.PI/2;ring.position.y=61;model.add(ring);rings.push({mesh:ring,offset:k*.5})}}
const halo=new THREE.Mesh(new THREE.RingGeometry(17,18,48),new THREE.MeshBasicMaterial({color:a.status==='Critical'?0xff7379:isPower?0xffc363:0x71caff,transparent:true,opacity:.65,side:THREE.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=2.8;model.add(halo);const beacon=new THREE.Mesh(new THREE.SphereGeometry(1.5,8,6),new THREE.MeshBasicMaterial({color:a.status==='Critical'?0xff6475:isPower?0xffcf73:0x93e0ff}));beacon.position.y=isPower?60:69;model.add(beacon);const hit=new THREE.Mesh(new THREE.CylinderGeometry(17,19,78,8),new THREE.MeshBasicMaterial({visible:false}));hit.position.y=37;hit.userData.asset=a;model.add(hit);hits.push(hit)}
if(connections){for(const type of ['Electricity','Telecom']){const list=assets.filter(a=>a.sector===type).sort((a,b)=>b.lat-a.lat);for(let i=1;i<list.length;i++){const a=point(list[i-1]),b=point(list[i]),power=type==='Electricity';for(const offset of power?[-8,8]:[0]){const start=a.clone().add(new THREE.Vector3(offset,power?43:3,0)),end=b.clone().add(new THREE.Vector3(offset,power?43:3,0));const middle=start.clone().lerp(end,.5);middle.y=power?25:58;const curve=new THREE.QuadraticBezierCurve3(start,middle,end);const line=new THREE.Mesh(new THREE.TubeGeometry(curve,28,power?.4:.7,4,false),new THREE.MeshBasicMaterial({color:power?0xd9a14d:0x319dde,transparent:true,opacity:.55}));scene.add(line);const particle=new THREE.Mesh(new THREE.SphereGeometry(power?1.8:2.1,7,5),new THREE.MeshBasicMaterial({color:power?0xffdc8f:0x99e4ff}));scene.add(particle);particles.push({mesh:particle,curve,offset:i*.13})}}}}
const labelObjects:{sprite:THREE.Sprite}[]=[];for(const [name,x,z] of [['RANGPUR',230,110],['RAJSHAHI',150,265],['DHAKA',365,400],['KHULNA',210,525],['BARISHAL',410,585],['SYLHET',600,205],['CHATTOGRAM',655,490],['MYMENSINGH',420,210]] as [string,number,number][]){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=48;const ctx=canvas.getContext('2d')!;ctx.font='500 21px Arial';ctx.fillStyle=dark?'#b8d7d6':'#426275';ctx.textAlign='center';ctx.fillText(name,128,30);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(canvas),transparent:true,depthTest:false,opacity:.78}));sprite.position.set(x-350,19,z-350);sprite.scale.set(90,17,1);scene.add(sprite);labelObjects.push({sprite})}
let focusTarget:THREE.Vector3|null=null;api.current={zoom:n=>{camera.position.sub(controls.target).multiplyScalar(n).add(controls.target);controls.update()},reset:()=>{focusTarget=null;controls.reset();setActive(null)},focus:id=>{const a=assets.find(a=>a.id===id);if(a){focusTarget=point(a);setActive(a);rotating.current=false;setMoving(false)}}};
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let hovered:string|null=null;let downX=0,downY=0;const pick=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);return raycaster.intersectObjects(hits,false)[0]?.object.userData.asset as MapAsset|undefined};const down=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY;focusTarget=null};const move=(e:PointerEvent)=>{const a=pick(e);if((a?.id||null)!==hovered){hovered=a?.id||null;setHover(a||null)}renderer.domElement.style.cursor=a?'pointer':'grab'};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-downX,e.clientY-downY)>6)return;const a=pick(e);if(a){setActive(a);callback.current(a)}};const leave=()=>{hovered=null;setHover(null)};const loss=(e:Event)=>{e.preventDefault();setFailed(true)};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointerleave',leave);renderer.domElement.addEventListener('webglcontextlost',loss);
const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;const start=performance.now();let last=0;const render=(now:number)=>{frame=requestAnimationFrame(render);if(now-last<30||document.hidden)return;last=now;const t=(now-start)/1000;controls.autoRotate=rotating.current&&!reduced;if(focusTarget){const delta=focusTarget.clone().sub(controls.target).multiplyScalar(.07);controls.target.add(delta);camera.position.add(delta);if(delta.length()<.05)focusTarget=null}controls.update();models.forEach((m,id)=>{const s=hovered===id?1.23:1;m.scale.lerp(new THREE.Vector3(s,s,s),.15)});rings.forEach(({mesh,offset})=>{const p=reduced?.35:(t*.32+offset)%1;mesh.scale.setScalar(1+p*2.2);(mesh.material as THREE.MeshBasicMaterial).opacity=(1-p)*.5});particles.forEach(p=>{p.mesh.position.copy(p.curve.getPoint(reduced?.4:(t*.16+p.offset)%1))});renderer.render(scene,camera)};frame=requestAnimationFrame(render);
return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();api.current=null;scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){const mats=Array.isArray(m.material)?m.material:[m.material];mats.forEach(mat=>{const tex=(mat as THREE.MeshStandardMaterial).map;if(tex)tex.dispose();mat.dispose()})}});renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointerleave',leave);renderer.domElement.removeEventListener('webglcontextlost',loss);renderer.dispose();renderer.domElement.remove()};
},[geo,key,dark,sector,division,connections]);
const shown=hover||active;
return <div className={'scene-shell '+(sector==='Electricity'?'energy-scene':sector==='Telecom'?'telco-scene':'combined-scene')}><div ref={host} className="webgl-host"/>{failed&&<div className="scene-fallback"><strong>3D rendering is unavailable on this device.</strong><button onClick={onFallback}>Open the interactive 2D map</button></div>}<div className="scene-top-label"><span className="scene-live-dot"/> {sector==='Electricity'?'ELECTRICITY GRID':sector==='Telecom'?'TELECOM NETWORK':'CONNECTED BANGLADESH'}<small>3D EXPLORER</small></div><div className="scene-controls"><button aria-label="Zoom in" onClick={()=>api.current?.zoom(.83)}><Plus size={17}/></button><button aria-label="Zoom out" onClick={()=>api.current?.zoom(1.2)}><Minus size={17}/></button><button aria-label="Reset 3D camera" onClick={()=>api.current?.reset()}><RotateCcw size={16}/></button><button aria-label={moving?'Pause rotation':'Auto-rotate map'} aria-pressed={moving} onClick={()=>setMoving(!moving)}>{moving?<Pause size={16}/>:<Play size={16}/>}</button></div>{shown&&<div className="scene-hover"><span className={shown.sector==='Electricity'?'electric-symbol':'telco-symbol'}>{shown.sector==='Electricity'?<Zap size={20}/>:<Radio size={20}/>}</span><div><strong>{shown.name}</strong><small>{shown.division} · {shown.kind}</small></div><button aria-label={'Inspect '+shown.name} onClick={()=>callback.current(shown)}><MoveUpRight size={17}/></button></div>}<div className="scene-asset-dock" aria-label="Focus a 3D infrastructure model">{assets.map(a=><button key={a.id} title={a.name} className={active?.id===a.id?'active':''} onClick={()=>api.current?.focus(a.id)}>{a.sector==='Electricity'?<Zap size={13}/>:<Radio size={13}/>}<span>{a.name.replace('Power Plant','').replace('Power Station','').replace('Network Hub','').replace('Grid Hub','').replace('Cable Landing Station','').replace('Headquarters','')}</span></button>)}{!assets.length&&<span>No assets match these layers.</span>}</div><div className="scene-help">Drag to orbit <span>·</span> Scroll to zoom <span>·</span> Select a structure</div></div>
}
