// Central Eye National Infrastructure Assets (Electricity & Telecom)
// Synthesized from official Power Grid Bangladesh PLC and BTRC gazette records

export interface InfrastructureAsset {
  id: string;
  name: string;
  sector: string;
  kind: string;
  division: string;
  lat: number;
  lon: number;
  owner: string;
  capacity: string;
  status: string;
  details?: string;
}

export const INFRASTRUCTURE_ASSETS: InfrastructureAsset[] = [
  // ==========================================
  // ELECTRICITY SECTOR ASSETS (Power Grid & BPDB)
  // ==========================================
  {
    id: 'P-PAYRA',
    name: 'Payra Ultra Supercritical Coal Power Plant',
    sector: 'Electricity',
    kind: 'Coal Thermal Power Plant',
    division: 'Barishal',
    lat: 21.99,
    lon: 90.28,
    owner: 'BCPCL / NWPGCL',
    capacity: '1,320 MW (2x660 MW)',
    status: 'Normal',
    details: 'Base-load coal power connected to 400kV Payra-Gopalganj-Aminbazar line',
  },
  {
    id: 'P-MATARBARI',
    name: 'Matarbari Ultra Supercritical Power Hub',
    sector: 'Electricity',
    kind: 'Coal Thermal Power Plant',
    division: 'Chattogram',
    lat: 21.70,
    lon: 91.88,
    owner: 'CPGCBL',
    capacity: '1,200 MW (2x600 MW)',
    status: 'Normal',
    details: 'Deep sea coal terminal & 400kV Matarbari-Anowara-Madunaghat evacuation',
  },
  {
    id: 'P-RAMPAL',
    name: 'Maitree Super Thermal Power Plant (Rampal)',
    sector: 'Electricity',
    kind: 'Coal Thermal Power Plant',
    division: 'Khulna',
    lat: 22.58,
    lon: 89.58,
    owner: 'BIFPCL (BPDB-NTPC)',
    capacity: '1,320 MW (2x660 MW)',
    status: 'Normal',
    details: 'Equipped with FGD and 400kV Rampal-Gopalganj transmission link',
  },
  {
    id: 'P-MEGHNAGHAT',
    name: 'Meghnaghat Combined Cycle Power Hub',
    sector: 'Electricity',
    kind: 'Gas / RLNG Combined Cycle',
    division: 'Dhaka',
    lat: 23.60,
    lon: 90.59,
    owner: 'Reliance / Summit / Unique',
    capacity: '2,165 MW Combined',
    status: 'Normal',
    details: 'High-efficiency H-Class & F-Class gas turbines feeding Dhaka metropolitan ring',
  },
  {
    id: 'P-ASHUGANJ',
    name: 'Ashuganj Power Station Complex',
    sector: 'Electricity',
    kind: 'Gas Turbine Power Station',
    division: 'Chattogram',
    lat: 24.04,
    lon: 91.01,
    owner: 'APSCL',
    capacity: '1,627 MW',
    status: 'Normal',
    details: 'Historic power hub supplying East-West interconnector and Dhaka corridor',
  },
  {
    id: 'P-GHORASHAL',
    name: 'Ghorashal Power Station',
    sector: 'Electricity',
    kind: 'Gas Thermal / Repowered CC',
    division: 'Dhaka',
    lat: 23.98,
    lon: 90.64,
    owner: 'BPDB',
    capacity: '1,215 MW',
    status: 'Watch',
    details: 'Unit 3 & 4 repowered combined cycle units under periodic maintenance',
  },
  {
    id: 'P-SIRAJGANJ',
    name: 'Sirajganj Combined Cycle Power Hub',
    sector: 'Electricity',
    kind: 'Dual Fuel Combined Cycle',
    division: 'Rajshahi',
    lat: 24.38,
    lon: 89.75,
    owner: 'NWPGCL / Sembcorp',
    capacity: '840 MW',
    status: 'Normal',
    details: 'Crucial generation node west of the Jamuna river',
  },
  {
    id: 'P-KAPTAI',
    name: 'Karnafuli Hydropower Generation Station',
    sector: 'Electricity',
    kind: 'Hydroelectric Power Plant',
    division: 'Chattogram',
    lat: 22.49,
    lon: 92.22,
    owner: 'BPDB',
    capacity: '230 MW (5 Units)',
    status: 'Normal',
    details: 'Only hydroelectric station in Bangladesh with black-start capability',
  },
  {
    id: 'P-BIBIYANA',
    name: 'Bibiyana Gas Power Complex (Units II & III)',
    sector: 'Electricity',
    kind: 'Gas Combined Cycle',
    division: 'Sylhet',
    lat: 24.63,
    lon: 91.43,
    owner: 'BPDB / Summit',
    capacity: '780 MW',
    status: 'Normal',
    details: 'Direct wellhead gas connection from Chevron Bibiyana field',
  },
  {
    id: 'P-BARAPUKURIA',
    name: 'Barapukuria Thermal Power Station',
    sector: 'Electricity',
    kind: 'Mine-Mouth Coal Power',
    division: 'Rangpur',
    lat: 25.55,
    lon: 88.95,
    owner: 'BPDB',
    capacity: '525 MW',
    status: 'Watch',
    details: 'Directly fed by Barapukuria Coal Mining Company Ltd (BCMCL)',
  },
  {
    id: 'P-ROOPPUR',
    name: 'Rooppur Nuclear Power Plant (Under Grid Sync)',
    sector: 'Electricity',
    kind: 'Nuclear Power Station (VVER-1200)',
    division: 'Rajshahi',
    lat: 24.07,
    lon: 89.05,
    owner: 'BAEC / Rosatom',
    capacity: '2,400 MW (2x1200 MW)',
    status: 'Watch',
    details: 'Unit 1 undergoing transmission line and safety commissioning',
  },
  {
    id: 'P-TEESTA-SOLAR',
    name: 'Teesta Solar Power Park',
    sector: 'Electricity',
    kind: 'Grid-tied Solar PV',
    division: 'Rangpur',
    lat: 25.68,
    lon: 89.54,
    owner: 'Beximco Solar / PGCB',
    capacity: '200 MW Peak',
    status: 'Normal',
    details: 'Largest operational utility-scale solar PV facility in Bangladesh',
  },
  {
    id: 'P-FENI-WIND',
    name: 'Feni Muhuri Dam Wind Farm',
    sector: 'Electricity',
    kind: 'Wind Energy Generation',
    division: 'Chattogram',
    lat: 22.84,
    lon: 91.38,
    owner: 'BPDB',
    capacity: '60 MW Project Zone',
    status: 'Normal',
    details: 'Coastal wind turbine installations at Muhuri Dam regulator',
  },
  {
    id: 'P-ADANI-IMPORT',
    name: 'Adani Godda Cross-Border HVDC Interconnector',
    sector: 'Electricity',
    kind: 'Cross-Border Transmission Corridor',
    division: 'Rajshahi',
    lat: 24.78,
    lon: 88.22,
    owner: 'Adani Power / PGCB',
    capacity: '1,600 MW (Dedicated 400kV)',
    status: 'Normal',
    details: '400kV dedicated transmission line entering via Rahanpur border to Bogra',
  },
  {
    id: 'P-BHERAMARA-HVDC',
    name: 'Bheramara HVDC Back-to-Back Substation',
    sector: 'Electricity',
    kind: 'Cross-Border Interconnection',
    division: 'Khulna',
    lat: 24.03,
    lon: 88.99,
    owner: 'Power Grid Bangladesh PLC',
    capacity: '1,000 MW (Bahrampur-Bheramara)',
    status: 'Normal',
    details: 'Primary bilateral HVDC link between Western Grid and POWERGRID India',
  },
  {
    id: 'P-TRIPURA-IMPORT',
    name: 'Tripura-Comilla 400kV Interconnection',
    sector: 'Electricity',
    kind: 'Cross-Border AC Transmission',
    division: 'Chattogram',
    lat: 23.46,
    lon: 91.18,
    owner: 'PGCB / TSECL',
    capacity: '160 MW (Surjamaninagar-Comilla)',
    status: 'Normal',
    details: 'Eastern grid link from ONGC Tripura gas plant into Comilla North 230kV hub',
  },
  {
    id: 'P-NLDC',
    name: 'Power Grid National Load Despatch Centre (NLDC)',
    sector: 'Electricity',
    kind: 'National Grid Control Centre',
    division: 'Dhaka',
    lat: 23.76,
    lon: 90.43,
    owner: 'Power Grid Bangladesh PLC',
    capacity: 'National Grid Control',
    status: 'Normal',
    details: 'Supervisory Control and Data Acquisition (SCADA) & EMS master station',
  },
  {
    id: 'P-AMINBAZAR',
    name: 'Aminbazar 400/230kV Super Grid Substation',
    sector: 'Electricity',
    kind: 'Super Grid Substation',
    division: 'Dhaka',
    lat: 23.79,
    lon: 90.31,
    owner: 'Power Grid Bangladesh PLC',
    capacity: '400/230/132 kV Node',
    status: 'Normal',
    details: 'Primary western intake receiving power from Payra and Rampal corridors',
  },
  {
    id: 'P-HATHAZARI',
    name: 'Hathazari 400/230kV Grid Substation',
    sector: 'Electricity',
    kind: 'Regional Super Substation',
    division: 'Chattogram',
    lat: 22.50,
    lon: 91.80,
    owner: 'Power Grid Bangladesh PLC',
    capacity: '400/230/132 kV Node',
    status: 'Normal',
    details: 'Central switching yard for Chattogram industrial belt and Matarbari power',
  },
  {
    id: 'P-BOGRA-GRID',
    name: 'Bogra 230/132kV Primary Transmission Hub',
    sector: 'Electricity',
    kind: 'Northern Transmission Substation',
    division: 'Rajshahi',
    lat: 24.85,
    lon: 89.37,
    owner: 'Power Grid Bangladesh PLC',
    capacity: '230/132 kV Node',
    status: 'Normal',
    details: 'Northern interconnection receiving Adani Godda and Barapukuria power',
  },
  {
    id: 'P-MYM-GRID',
    name: 'Mymensingh 132/33kV Central Substation',
    sector: 'Electricity',
    kind: 'Regional Distribution Substation',
    division: 'Mymensingh',
    lat: 24.75,
    lon: 90.40,
    owner: 'Power Grid Bangladesh PLC',
    capacity: '132/33 kV Node',
    status: 'Normal',
    details: 'Key grid feeder for Jamalpur, Netrokona and agricultural pumping loads',
  },

  // ==========================================
  // TELECOM SECTOR ASSETS (BTRC & Operators)
  // ==========================================
  {
    id: 'T-BTRC-HQ',
    name: 'BTRC Headquarters & National Spectrum Management',
    sector: 'Telecom',
    kind: 'Regulatory & Spectrum NOC',
    division: 'Dhaka',
    lat: 23.78,
    lon: 90.42,
    owner: 'BTRC',
    capacity: 'National Spectrum 406.6 MHz',
    status: 'Normal',
    details: 'Central frequency assignment, QoS reconciliation, and telecom licensing',
  },
  {
    id: 'T-SMW4',
    name: 'Cox’s Bazar Submarine Cable Landing Station (SEA-ME-WE 4 & 6)',
    sector: 'Telecom',
    kind: 'International Cable Landing Station',
    division: 'Chattogram',
    lat: 21.43,
    lon: 91.98,
    owner: 'BSCPLC',
    capacity: 'SMW-4 (300G) + SMW-6 (13.2 Tbps)',
    status: 'Watch',
    details: 'Primary eastern international gateway with redundant terrestrial NTTN backhaul',
  },
  {
    id: 'T-SMW5',
    name: 'Kuakata Submarine Cable Landing Station (SEA-ME-WE 5)',
    sector: 'Telecom',
    kind: 'International Cable Landing Station',
    division: 'Barishal',
    lat: 21.84,
    lon: 90.12,
    owner: 'BSCPLC',
    capacity: 'SEA-ME-WE 5 (1,500 Gbps)',
    status: 'Normal',
    details: 'Southern submarine gateway providing geographical diversity and resilience',
  },
  {
    id: 'T-GP-NOC',
    name: 'Grameenphone Central Data Center & Core NOC',
    sector: 'Telecom',
    kind: 'Tier-III Operator Core NOC',
    division: 'Dhaka',
    lat: 23.82,
    lon: 90.43,
    owner: 'Grameenphone (Telenor)',
    capacity: '87.01M Subscribers · 11,788 Towers',
    status: 'Normal',
    details: 'Managing 117.4 MHz spectrum with nationwide 4G and 5G testbeds',
  },
  {
    id: 'T-ROBI-NOC',
    name: 'Robi Axiata National Network Operations Center',
    sector: 'Telecom',
    kind: 'Operator Core NOC & Cloud Hub',
    division: 'Dhaka',
    lat: 23.79,
    lon: 90.41,
    owner: 'Robi Axiata (Axiata Group)',
    capacity: '58.77M Subscribers · 2,185 Towers',
    status: 'Normal',
    details: 'Operating 104.0 MHz spectrum and extensive 4.5G dynamic spectrum sharing',
  },
  {
    id: 'T-BL-NOC',
    name: 'Banglalink Tigers Den Core Switching Center',
    sector: 'Telecom',
    kind: 'Operator Core Switch & Data Center',
    division: 'Dhaka',
    lat: 23.79,
    lon: 90.40,
    owner: 'Banglalink (VEON)',
    capacity: '37.84M Subscribers · 3,905 Towers',
    status: 'Normal',
    details: '80.0 MHz spectrum with 40 MHz in 2.3 GHz for high-capacity urban 4G',
  },
  {
    id: 'T-TELETALK-NOC',
    name: 'Teletalk Bangladesh National Network Center',
    sector: 'Telecom',
    kind: 'State Operator Core NOC',
    division: 'Dhaka',
    lat: 23.79,
    lon: 90.41,
    owner: 'Teletalk Bangladesh Ltd',
    capacity: '6.82M Subscribers · 3,490 Towers',
    status: 'Normal',
    details: 'Government cellular operator with 65.2 MHz allocated spectrum',
  },
  {
    id: 'T-EDOTCO-HUB',
    name: 'edotco Bangladesh National Tower Operations Hub',
    sector: 'Telecom',
    kind: 'Tower Sharing Operator (TowerCo)',
    division: 'Dhaka',
    lat: 23.87,
    lon: 90.39,
    owner: 'edotco Bangladesh',
    capacity: '16,984 Shared Towers',
    status: 'Normal',
    details: 'Largest tower company in Bangladesh with smart energy solar hybrid sites',
  },
  {
    id: 'T-SUMMIT-TOWER',
    name: 'Summit Towers Regional Hub & Core BTS Cluster',
    sector: 'Telecom',
    kind: 'Tower Sharing Operator (TowerCo)',
    division: 'Chattogram',
    lat: 22.36,
    lon: 91.82,
    owner: 'Summit Towers Ltd',
    capacity: '5,593 Shared Towers',
    status: 'Normal',
    details: 'Extensive coverage along Dhaka-Chattogram economic corridor',
  },
  {
    id: 'T-KIRTONKHOLA',
    name: 'Kirtonkhola Tower Operations Center',
    sector: 'Telecom',
    kind: 'Tower Sharing Operator (TowerCo)',
    division: 'Barishal',
    lat: 22.70,
    lon: 90.36,
    owner: 'Kirtonkhola Tower Technologies',
    capacity: '1,212 Shared Towers',
    status: 'Normal',
    details: 'Coastal & riverine tower infrastructure across Barishal division',
  },
  {
    id: 'T-FRONTIER',
    name: 'Frontier Towers Northern Regional Operations',
    sector: 'Telecom',
    kind: 'Tower Sharing Operator (TowerCo)',
    division: 'Rajshahi',
    lat: 24.36,
    lon: 88.62,
    owner: 'Frontier Towers Bangladesh',
    capacity: '939 Shared Towers',
    status: 'Normal',
    details: 'Northern tower rollout supporting co-location and 4G densification',
  },
  {
    id: 'T-BTCL-MOGBAZAR',
    name: 'BTCL Central Telecommunications Exchange (Mogbazar)',
    sector: 'Telecom',
    kind: 'National Core Transmission & PSTN',
    division: 'Dhaka',
    lat: 23.75,
    lon: 90.41,
    owner: 'BTCL',
    capacity: '514 Towers · 79,083 km Govt Fiber',
    status: 'Normal',
    details: 'Central routing for government Info-Sarker and National Internet Exchange',
  },
  {
    id: 'T-FIBERATHOME',
    name: 'Fiber@Home Central NTTN Optical Transmission Hub',
    sector: 'Telecom',
    kind: 'Nationwide NTTN Optical Backbone',
    division: 'Dhaka',
    lat: 23.77,
    lon: 90.41,
    owner: 'Fiber@Home Ltd',
    capacity: '50,000+ km Optical Fiber',
    status: 'Normal',
    details: 'Private NTTN providing DWDM backbone linking all 64 district headquarters',
  },
  {
    id: 'T-SUMMIT-FIBER',
    name: 'Summit Communications NTTN Gateway',
    sector: 'Telecom',
    kind: 'Nationwide NTTN Optical Backbone',
    division: 'Dhaka',
    lat: 23.79,
    lon: 90.42,
    owner: 'Summit Communications Ltd',
    capacity: '48,000+ km Optical Fiber',
    status: 'Normal',
    details: 'Overhead & underground high-capacity optical fiber transmission grid',
  },
  {
    id: 'T-SYLHET-HUB',
    name: 'Sylhet Regional Optical Fiber Aggregation Center',
    sector: 'Telecom',
    kind: 'Regional Telecom Aggregation Hub',
    division: 'Sylhet',
    lat: 24.89,
    lon: 91.87,
    owner: 'BTCL / NTTN Response',
    capacity: 'Regional Fiber Node · 350+ BTS',
    status: 'Critical',
    details: 'Undergoing active fiber splice restoration following road excavation',
  },
  {
    id: 'T-KHULNA-NODE',
    name: 'Khulna Regional Telecom Switching Center',
    sector: 'Telecom',
    kind: 'Regional Telecom Exchange & Gateway',
    division: 'Khulna',
    lat: 22.82,
    lon: 89.55,
    owner: 'BTCL / Operators Hub',
    capacity: 'South-Western Optical Trunk',
    status: 'Normal',
    details: 'Major gateway connecting Mongla Port, Bheramara, and Kuakata SMW-5',
  },
  {
    id: 'T-RANGPUR-TOWER',
    name: 'Rangpur Regional Microwave & Tower Complex',
    sector: 'Telecom',
    kind: 'Regional Transmission Node',
    division: 'Rangpur',
    lat: 25.74,
    lon: 89.27,
    owner: 'edotco / Teletalk',
    capacity: 'Northern Frontier Transmission',
    status: 'Normal',
    details: 'Long-haul optical and microwave relays connecting northern border areas',
  },
  {
    id: 'T-MYM-NODE',
    name: 'Mymensingh Digital Transmission & QoS Post',
    sector: 'Telecom',
    kind: 'Regional QoS & Network Node',
    division: 'Mymensingh',
    lat: 24.76,
    lon: 90.39,
    owner: 'BTRC / Operators Shared Hub',
    capacity: 'Regional Drive-Test & Audit Base',
    status: 'Normal',
    details: 'Monitoring call drop rates and 4G throughput compliance for Mymensingh',
  },
  {
    id: 'T-INFOSARKER-CORE',
    name: 'Info-Sarker Phase-III Union Digital Center Hub',
    sector: 'Telecom',
    kind: 'Government Rural Broadband Node',
    division: 'Dhaka',
    lat: 23.01,
    lon: 89.83,
    owner: 'ICT Division / BCC',
    capacity: '2,600+ Union Parishads Connected',
    status: 'Normal',
    details: 'Underground optical fiber extension delivering broadband to rural unions',
  },
  {
    id: 'T-VOIP-SURVEILLANCE',
    name: 'BTRC Central Anti-VoIP Cyber Monitoring Facility',
    sector: 'Telecom',
    kind: 'Enforcement & Spectrum Monitoring',
    division: 'Dhaka',
    lat: 23.77,
    lon: 90.38,
    owner: 'BTRC Enforcement Division',
    capacity: '14.25M Illegal SIMs Neutralized',
    status: 'Normal',
    details: 'Automated CDR analysis detecting illegal SIM boxes and unregistered VoIP routes',
  },
];
